TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851

spring:
  datasource:
    url: ${NAIS_DATABASE_KABAL_TEXT_TEMPLATES_PRIV_KABAL_TEXT_TEMPLATES_JDBC_URL}
    hikari:
      maximum-pool-size: 5

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
