spring:
  application:
    name: kabal-text-templates
  main:
    banner-mode: OFF
  mvc:
    throw-exception-if-no-handler-found: true
  lifecycle:
    timeout-per-shutdown-phase: 20s
  servlet:
    multipart:
      max-request-size: 8MB
      max-file-size: 8MB
  codec:
    max-in-memory-size: 16MB
  datasource:
    url: jdbc:postgresql://${NAIS_DATABASE_KABAL_TEXT_TEMPLATES_KABAL_TEXT_TEMPLATES_HOST}:${NAIS_DATABASE_KABAL_TEXT_TEMPLATES_KABAL_TEXT_TEMPLATES_PORT}/${NAIS_DATABASE_KABAL_TEXT_TEMPLATES_KABAL_TEXT_TEMPLATES_DATABASE}
    username: ${NAIS_DATABASE_KABAL_TEXT_TEMPLATES_KABAL_TEXT_TEMPLATES_USERNAME}
    password: ${NAIS_DATABASE_KABAL_TEXT_TEMPLATES_KABAL_TEXT_TEMPLATES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    clean-on-validation-error: false
    schemas: flyway_history_schema,klage
  sql:
    init:
      platform: postgresql
  web:
    resources:
      add-mappings: false
  data:
    redis:
      host: redis-klage-texts-nav-dev.h.aivencloud.com
      port: 26483
      password: ${REDIS_PASSWORD_TEXTS}
      username: ${REDIS_USERNAME_TEXTS}
      ssl:
        enabled: true

server:
  port: 7096
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 5KB

navCallIdName: Nav-Callid

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    baggage:
      remote-fields:
        - ${navCallIdName}
      correlation:
        fields:
          - ${navCallIdName}
  health:
    redis:
      enabled: false
no.nav.security.jwt:
  issuer:
    aad:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
  client:
    registration:
      azure-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: https://graph.microsoft.com/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
