TENANT_ID: 62366534-1ec3-4962-8869-9b5535279d0b

spring:
  datasource:
    url: jdbc:postgresql://${NAIS_DATABASE_KABAL_TEXT_TEMPLATES_KABAL_TEXT_TEMPLATES_HOST}:${NAIS_DATABASE_KABAL_TEXT_TEMPLATES_KABAL_TEXT_TEMPLATES_PORT}/${NAIS_DATABASE_KABAL_TEXT_TEMPLATES_KABAL_TEXT_TEMPLATES_DATABASE}
    username: ${NAIS_DATABASE_KABAL_TEXT_TEMPLATES_KABAL_TEXT_TEMPLATES_USERNAME}
    password: ${NAIS_DATABASE_KABAL_TEXT_TEMPLATES_KABAL_TEXT_TEMPLATES_PASSWORD}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
