TENANT_ID: 62366534-1ec3-4962-8869-9b5535279d0b

spring:
  datasource:
    url: ${NAIS_DATABASE_KABAL_TEXT_TEMPLATES_PRIV_KABAL_TEXT_TEMPLATES_JDBC_URL}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
