TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851

spring:
  datasource:
    url: jdbc:postgresql://${NAIS_DATABASE_KABAL_TEXT_TEMPLATES_KABAL_TEXT_TEMPLATES_HOST}:${NAIS_DATABASE_KABAL_TEXT_TEMPLATES_KABAL_TEXT_TEMPLATES_PORT}/${NAIS_DATABASE_KABAL_TEXT_TEMPLATES_KABAL_TEXT_TEMPLATES_DATABASE}
    username: ${NAIS_DATABASE_KABAL_TEXT_TEMPLATES_KABAL_TEXT_TEMPLATES_USERNAME}
    password: ${NAIS_DATABASE_KABAL_TEXT_TEMPLATES_KABAL_TEXT_TEMPLATES_PASSWORD}
    hikari:
      maximum-pool-size: 5

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
