ingresses:
  - https://kabal-text-templates.dev.intern.nav.no
  - https://kabal-text-templates.intern.dev.nav.no
externalHosts:
springProfile: dev-gcp
db_tier: db-custom-1-3840
db_size: 10
db_ha: true
tenant: trygdeetaten.no

envs:
  - name: JAVA_TOOL_OPTIONS
    value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  - name: JAVA_OPTS
    value: "-Xms512m -Xmx4096m"