ingresses:
  - https://kabal-text-templates.intern.dev.nav.no
externalHosts:
springProfile: dev-gcp
db_tier: db-f1-micro
db_size: 10
db_ha: false
db_type: POSTGRES_15
tenant: trygdeetaten.no

spring:
  datasource:
    hikari:
      maximum-pool-size: 5

envs:
  - name: JAVA_TOOL_OPTIONS
    value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  - name: JAVA_OPTS
    value: "-Xms256m -Xmx4096m"
