ingresses:
  - https://kabal-text-templates.dev.intern.nav.no
externalHosts:
springProfile: dev-gcp
db_tier: db-custom-1-3840
db_size: 10
db_ha: true
tenant: trygdeetaten.no

roles:
  - 94d34f17-e325-4ed6-9667-d23041a3f40c # ROLE_KLAGE_FAGANSVARLIG
  - a9f5ef81-4e81-42e8-b368-0273071b64b9 # ROLE_ADMIN / ROLE_GOSYS_OPPGAVE_BEHANDLER (dev is weird)

envs:
  - name: JAVA_TOOL_OPTIONS
    value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  - name: JAVA_OPTS
    value: "-Xms512m -Xmx4096m"